# Generated by Django 6.1.1 on 2026-09-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name="Narxi (so'm)")),
                ('image', models.ImageField(upload_to='menu_images/', verbose_name='Rasm')),
                ('is_active', models.BooleanField(default=True, verbose_name="Ko'rinadimi")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Taom',
                'verbose_name_plural': 'Taomlar',
                'ordering': ['order', 'name'],
            },
        ),
    ]
