# Generated by Django 5.0.7 on 2026-09-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='bg/bg.jpg', verbose_name='Fon rasmi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='cafe_name',
            field=models.CharField(blank=True, default='SUSAMBIL', max_length=200, verbose_name='Kafe nomi'),
        ),
    ]
