# Generated by Django 5.0.7 on 2026-09-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_sitesettings_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Tavsif'),
        ),
    ]